name: cortado_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.12.0+2
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  path_provider: ^1.6.1
  url_launcher: ^5.4.2
  path: ^1.6.4
  linkify: ^2.0.3
  flutter_linkify: ^3.1.0
  get_it: ^3.1.0

 # GEOLOCATION
  geolocator: ^5.1.3
  geocoder: ^0.2.1
  location: ^1.4.1
  
 
  # FIREBASE
  firebase_core: 0.4.0+9
  firebase_auth: 0.14.0+5
  firebase_storage: 3.0.6
  firebase_messaging: 5.1.6
  firebase_dynamic_links: 0.5.0+1
  cloud_firestore: 0.12.9+4
  
  
  
  
  # ROUTING
  fluro: ^1.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  supernova_flutter_ui_toolkit: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cortado-logo-3.png
    - assets/images/welcome-screen-3.png
    - assets/images/cortado-splash.png
    - assets/images/cortado-splash-dark.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/.15708.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
